import Foundation

/// Primitive views have a `Body` type of `Never` and have custom logic for
/// building and updating nodes created for them in the view graph.
///
/// Primitive views have complete control of how they build and update nodes. Note that a view is
/// a description of how to create a **list** of controls. There are various types of primitive
/// views:
///
/// * Ones that manage a single control, or that let a user specify a collection of other views.
///
/// * Ones that work as modifiers, changing the controls that an underlying view generates
///   individually. Those primitive views additionally conform to the `ModifierView` protocol.
///
/// * Ones that define a container for the controls generated by the underlying view. They can
///   load the controls lazily. Those primitive views additionally conform to the `LayoutRootView`
///   protocol.
protocol PrimitiveView: View where Body == Never {
    func buildNode(_ node: ViewNode<Self>)
    func updateNode(_ node: ViewNode<Self>)
    static var size: Int? { get }
}

extension PrimitiveView {
    public var body: Never { fatalError("Cannot evaluate `\(Self.self).body` of type Never") }
}

extension View {
    static var size: Int? {
        if let I = Self.self as? (any PrimitiveView.Type) {
            return I.size
        }
        return Body.size
    }
}

extension View {
    func buildNode(_ node: ViewNode<Self>) {
        if let primitive = self as? (any PrimitiveView) {
            func _buildNode<T: PrimitiveView>(_ view: T) {
                view.buildNode(unsafeDowncast(node, to: ViewNode<T>.self))
            }
           _buildNode(primitive)
        } else {
            self.setupStateProperties(node: node)
            self.setupEnvironmentProperties(node: node)
            #if os(macOS)
            self.setupObservedObjectProperties(node: node)
            #endif
            node.addNode(at: 0, ViewNode(view: self.body))
        }
    }

    func updateNode(_ node: ViewNode<Self>) {
        if let primitive = self as? (any PrimitiveView) {
            func _updateNode<T: PrimitiveView>(_ view: T) {
                view.updateNode(unsafeDowncast(node, to: ViewNode<T>.self))
            }
           _updateNode(primitive) 
        } else {
            self.setupStateProperties(node: node)
            self.setupEnvironmentProperties(node: node)
            node.view = self
            node.children[0].update(using: self.body)
        }
    }
}